## Zach Holcomb AI/ML Project Portfolio

##### [Article Fact Checking](https://github.com/holcombzv/ml_ai_portfolio/tree/main/fact_checking)

As a personal project, I created a recurrant neural network from scratch that can predict whether a news article contains real or fake news. I achieved an accuracy of 97.5%. Methods used include data formatting and tokenization, long short-term memory, and dropout layers.

##### [Road Sign Recognition](https://github.com/holcombzv/ml_ai_portfolio/tree/main/road_signs)

My contributions to this project include training a neural network to recognize German road signs using transfer learning, convolutional layers, and data augmentation.

The model achieved an accuracy of 96%, a great start for use in self driving cars.

##### [Banco Federal de Financas Marketing Campain Analysis](https://github.com/holcombzv/ml_ai_portfolio/tree/main/banco_federal_marketing)
Me and my team were asked to evaluate the effectiveness of our client's marketing campaign to get customers to subscribe to a term deposit. We were also tasked with creating a decision tree ML model to predict which customers were most likely to subscribe.

Using our analasys and model, which achieved 82% accuracy, we reduced the call list size by 30% without compromising subscription rates, optimizing resource allocation. We also provided 3 key trends to act on to further optimize their strategy.

##### [Housing Prices Prediction](https://github.com/holcombzv/ml_ai_portfolio/tree/main/home_prices)

As part of a team, I created a random forest model that predicts the price of a home in Seattle, WA, using features such as location, construction quality, year built, and various home features. 

Our model surpassed expectations with an R² of .91 and was accurate within $100,000 of the actual price. Time savings for real estate professionals would be up to 8-12 hours weekly with significant potential to increase profitability by targeting high-value properties effectively.

##### [Text Generation](https://github.com/holcombzv/ml_ai_portfolio/tree/main/text_generation)

Building off of code we recieved from a previous team, my team and I built a model to generate text replicating the style of various popular authors. The model understands grramar and syntax, but still forms incoherent sentances. The best way to improve this model would be to use transfer learning off a more advanced model such as GPT2.